name: firebase_image
description: A cached Flutter ImageProvider for Firebase Cloud Storage image objects.
version: 1.1.2
homepage: https://github.com/mattreid1/firebase_image

environment:
  sdk: ^3.5.0
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  sqflite: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
